import { defaultPoses } from '../fighter/poses'
import type { CharacterDef, MoveDef, Palette } from '../types'
import { baseMoves } from './common'

/** THE INTERN — unpaid, over-caffeinated, all kicks. The balanced all-rounder. */

const coffeeSplash: MoveDef = {
  id: 'coffeeSplash',
  name: 'Coffee Splash',
  startup: 10,
  active: 8,
  recovery: 18,
  damage: 0,
  hitstun: 0,
  blockstun: 0,
  pushHit: 0,
  pushBlock: 0,
  hitstop: 0,
  level: 'mid',
  spawn: { frame: 10, kind: 'coffee' },
  poses: {
    startup: {
      hip: [-1, 27],
      lean: -8,
      nearLeg: { ik: [-9, 2] },
      farLeg: { ik: [8, 2] },
      nearArm: { a: [-70, -30] },
      farArm: { ik: [14, 44] },
    },
    active: {
      hip: [2, 26],
      lean: 14,
      face: 'shout',
      nearLeg: { ik: [-10, 2] },
      farLeg: { ik: [10, 2] },
      nearArm: { a: [100, 95] },
      farArm: { a: [-30, -10] },
    },
    recover: {
      hip: [1, 26],
      lean: 10,
      nearLeg: { ik: [-9, 2] },
      farLeg: { ik: [9, 2] },
      nearArm: { a: [80, 60] },
      farArm: { ik: [12, 42] },
    },
  },
}

const base = {
  outline: '#1a1020',
  eye: '#ffffff',
  accent: '#1a1020',
  prop: '#444444',
  propShade: '#222222',
  propB: '#dddddd',
  propDark: '#111111',
}

const palettes: Palette[] = [
  {
    ...base,
    id: 'intern-a',
    skin: '#f2c089',
    skinShade: '#c98a55',
    hair: '#3a2418',
    hairShade: '#22140c',
    top: '#f4f4ee',
    topShade: '#a9b1c4',
    jacket: '#f4f4ee',
    jacketShade: '#a9b1c4',
    legs: '#4a4f5e',
    legsShade: '#2e3140',
    shoe: '#1e1a1a',
    shoeShine: '#5a5252',
    tie: '#d62828',
    tieShade: '#8e1616',
    belt: '#2a1a12',
  },
  {
    ...base,
    id: 'intern-b',
    skin: '#c68a5a',
    skinShade: '#8e5a34',
    hair: '#101014',
    hairShade: '#000000',
    top: '#9fd0f0',
    topShade: '#5f89b8',
    jacket: '#9fd0f0',
    jacketShade: '#5f89b8',
    legs: '#6b4a2e',
    legsShade: '#46301c',
    shoe: '#3a2212',
    shoeShine: '#7a5236',
    tie: '#1f3b8c',
    tieShade: '#0f1f52',
    belt: '#1a120c',
  },
]

export const intern: CharacterDef = {
  id: 'intern',
  name: 'INTERN',
  title: 'The Unpaid Intern',
  bio: 'Runs on free coffee and hope. Quick kicks, no fear, no salary.',
  stats: { health: 105, power: 3, walkF: 1.7, walkB: 1.3, jumpV: 5.4, jumpVX: 1.9 },
  body: {
    thigh: 15,
    shin: 15,
    upperArm: 11,
    foreArm: 10,
    torso: 20,
    neck: 3,
    headR: 9,
    shoulderW: 20,
    hipW: 15,
    thighW: 9,
    shinW: 7,
    armW: 6,
    foreW: 5,
  },
  look: {
    hair: 'short',
    top: 'shirt',
    tie: true,
    skirt: false,
    belly: 0,
    shoes: 'flat',
    glasses: false,
    beard: false,
    lipstick: false,
    grin: false,
    logo: false,
    prop: 'none',
  },
  hurtHalfW: 12,
  palettes,
  poses: defaultPoses,
  moves: baseMoves,
  special: {
    move: coffeeSplash,
    seq: ['D', 'F'],
    button: 'lk',
    cooldown: 70,
    label: '↓ → X',
    description: 'Throws a scalding cup of office coffee.',
  },
}
